name: budgetBlocks
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2
  get: ^4.6.5
  hive: ^2.2.3
  http: ^0.13.5
  path_provider: ^2.0.13
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:


  uses-material-design: true

  assets:
    - assets/image/app_barr_logo.png
    - assets/wallet_page/
    - assets/landing/
    - assets/homeicon/ 
  fonts:
    - family: Righteous
      fonts:
        - asset: assets/font/Righteous-Regular.ttf
    - family: RedHatDisplay
      fonts:
        - asset: assets/font/RedHatDisplay.ttf
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat.ttf
 